[package]
name = "AirdropClaim"
version = "0.1.0"

[addresses]
airdrop = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
